version: '2.4'

services:
  mastodon:
    build: .
    ports:
      - 3000
      - 4000
      - 80:8000
    environment:
      - LOCAL_DOMAIN=localhost
      - LOCAL_HTTPS=false
      - POSTGRESQL_HOST=postgres
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - REDIS_HOST=redis
    volumes:
      - data:/app/data
    tmpfs:
      - /run
      - /tmp
    read_only: true
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis

volumes:
  data: